import { defineField, defineType } from "sanity";

export const siteContent = defineType(
  {
    name: "siteContent",
    title: "Site Content",
    type: "document",
    __experimental_actions: ["update", "publish"],
    groups: [
      { name: "hero", title: "Homepage hero", default: true },
      { name: "sections", title: "Homepage sections" },
      { name: "intros", title: "Page intros" },
    ],
    fields: [
      defineField({
        name: "heroEyebrow",
        title: "Small green line above the headline",
        type: "string",
        group: "hero",
        validation: (rule) => rule.max(60),
      }),
      defineField({
        name: "heroHeadingMobile",
        title: "Headline (mobile)",
        description: "Shown on phones. Google reads this version, so keep the key words in it.",
        type: "string",
        group: "hero",
        validation: (rule) => rule.max(40),
      }),
      defineField({
        name: "heroHeadingDesktop",
        title: "Headline (desktop)",
        type: "string",
        group: "hero",
        validation: (rule) => rule.max(50),
      }),
      defineField({
        name: "heroSubheading",
        title: "Sentence below the headline",
        type: "text",
        rows: 2,
        group: "hero",
        validation: (rule) => rule.max(120),
      }),
      defineField({
        name: "heroEyebrowMobile",
        title: "Hero eyebrow (mobile)",
        type: "string",
        group: "hero",
        validation: (rule) => rule.max(80),
      }),
      defineField({
        name: "heroSubheadingMobile",
        title: "Hero subheading (mobile)",
        type: "text",
        rows: 3,
        group: "hero",
        validation: (rule) => rule.max(180),
      }),
      defineField({
        name: "quickActionsTitle",
        title: "Quick actions heading",
        type: "string",
        group: "hero",
        initialValue: "What are you looking for?",
        validation: (rule) => rule.max(60),
      }),
      defineField({
        name: "section1TitleStart",
        title: "Top Opportunities — Title start",
        type: "string",
        group: "sections",
        validation: (rule) => rule.max(30),
      }),
      defineField({
        name: "section1TitleAccent",
        title: "Top Opportunities — Accent word",
        description: "Shown in the accent colour",
        type: "string",
        group: "sections",
        validation: (rule) => rule.max(30),
      }),
      defineField({
        name: "section1Subtitle",
        title: "Top Opportunities — Subtitle",
        type: "string",
        group: "sections",
        validation: (rule) => rule.max(90),
      }),
      defineField({
        name: "section2TitleStart",
        title: "Most undersold ending soon — Title start",
        type: "string",
        group: "sections",
        validation: (rule) => rule.max(30),
      }),
      defineField({
        name: "section2TitleAccent",
        title: "Most undersold ending soon — Accent word",
        description: "Shown in the accent colour",
        type: "string",
        group: "sections",
        validation: (rule) => rule.max(30),
      }),
      defineField({
        name: "section2Subtitle",
        title: "Most undersold ending soon — Subtitle",
        type: "string",
        group: "sections",
        validation: (rule) => rule.max(90),
      }),
      defineField({
        name: "section3TitleStart",
        title: "Recent draws — Title start",
        type: "string",
        group: "sections",
        validation: (rule) => rule.max(30),
      }),
      defineField({
        name: "section3TitleAccent",
        title: "Recent draws — Accent word",
        description: "Shown in the accent colour",
        type: "string",
        group: "sections",
        validation: (rule) => rule.max(30),
      }),
      defineField({
        name: "section3Subtitle",
        title: "Recent draws — Subtitle",
        type: "string",
        group: "sections",
        validation: (rule) => rule.max(90),
      }),
      defineField({
        name: "section4TitleStart",
        title: "Top Prizes right now — Title start",
        type: "string",
        group: "sections",
        validation: (rule) => rule.max(30),
      }),
      defineField({
        name: "section4TitleAccent",
        title: "Top Prizes right now — Accent word",
        description: "Shown in the accent colour",
        type: "string",
        group: "sections",
        validation: (rule) => rule.max(30),
      }),
      defineField({
        name: "section4Subtitle",
        title: "Top Prizes right now — Subtitle",
        type: "string",
        group: "sections",
        validation: (rule) => rule.max(90),
      }),
      defineField({
        name: "section5TitleStart",
        title: "Selling fast — Title start",
        type: "string",
        group: "sections",
        validation: (rule) => rule.max(30),
      }),
      defineField({
        name: "section5TitleAccent",
        title: "Selling fast — Accent word",
        description: "Shown in the accent colour",
        type: "string",
        group: "sections",
        validation: (rule) => rule.max(30),
      }),
      defineField({
        name: "section5Subtitle",
        title: "Selling fast — Subtitle",
        type: "string",
        group: "sections",
        validation: (rule) => rule.max(90),
      }),
      defineField({
        name: "section6TitleStart",
        title: "Ending today — Title start",
        type: "string",
        group: "sections",
        validation: (rule) => rule.max(30),
      }),
      defineField({
        name: "section6TitleAccent",
        title: "Ending today — Accent word",
        description: "Shown in the accent colour",
        type: "string",
        group: "sections",
        validation: (rule) => rule.max(30),
      }),
      defineField({
        name: "section6Subtitle",
        title: "Ending today — Subtitle",
        type: "string",
        group: "sections",
        validation: (rule) => rule.max(90),
      }),
      defineField({
        name: "competitionsIntro",
        title: "Competitions page intro",
        type: "text",
        rows: 2,
        group: "intros",
        validation: (rule) => rule.max(200),
      }),
      defineField({
        name: "operatorsIntro",
        title: "Operators page intro",
        type: "text",
        rows: 2,
        group: "intros",
        validation: (rule) => rule.max(200),
      }),
      defineField({
        name: "reviewsIntro",
        title: "Reviews page intro",
        type: "text",
        rows: 2,
        group: "intros",
        validation: (rule) => rule.max(200),
      }),
      defineField({
        name: "blogIntro",
        title: "Blog page intro",
        type: "text",
        rows: 2,
        group: "intros",
        validation: (rule) => rule.max(200),
      }),
    ],
  },
  { strict: false },
);
